### PR TITLE
fix: avoid global variable usage

### LINKED ISSUE #425: Do not use global variables (`MPairs`)
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when my global namespace gets cluttered with unnecessary variables.

**Describe the solution you'd like**
Since compe is long archived and nothing else uses that global var, just remove https://github.com/windwp/nvim-autopairs/blob/master/lua/nvim-autopairs.lua#L662

### PR DESCRIPTION
**Pull request by JosefLitos**
fixes #425

### CODE REVIEW

**Comment by windwp** [comment]
Thank

**Comment by zeertzjq** [comment]
Hmm, this is a breaking change.

**Comment by JosefLitos** [comment]
Hmm, I thought I checked everything. From what I've found, all uses were withing the plugin internals. That shouldn't affect the user because they don't have direct access (or at least, I believe, have no reason to use it directly). Is there something I can help with?

**Comment by zeertzjq** [comment]
Well, I used `v:lua.MPairs` directly in my mappings. Replacing them with `v:lua.require'nvim-autopairs'` will work, although I just discovered a bug in Nvim that causes it to error sometimes.

**Comment by JosefLitos** [comment]
You can call it the same way I made the changes in the plugin - as a `<Cmd>` or a function callback. Though it is something that users using the global directly do have to change.

**Comment by stancl** [comment]
These changes seems to make neovim freeze when the plugin's behavior is triggered, see comments on 2e8a10c5fc0dcaf8296a5f1a7077efcd37065cc8

**Pull request merged**
