### PR TITLE
fix: support for close triple quotes

### PR DESCRIPTION
**Pull request by seblj**
This PR adds an option to close triple quotes like requested in several issues. As this in some special cases could provide unwanted results for some peope, I added this as an option that is default turned off. It could probably be done in a smarter way, but I think this would improve on how this is currently handled.

### CODE REVIEW

**Comment by windwp** [comment]
Thank 
It is my first lua plugin  and I design to support 1 character pairs so my code is not looking good it use too many if condition .
but it still work so i will merge.
#30

**Comment by chmanie** [comment]
Hey, thanks for adding this! For some reason it doesn't seem to have any effect for me.

I initialized like this:

```
require('nvim-autopairs').setup({close_triple_quotes = true})
```

But this is what happens when editing markdown:



Am I missing anything?

**Comment by seblj** [comment]
It seems like this plugin is completely redesigned since I made this PR, and the option is now gone. It now seems to be supported by default and is only used in certain filetypes. Try to open a markdown file and see if it works there

**Comment by chmanie** [comment]
Okay, it's because I'm using vimwiki. I'll submit a PR to support that as well.

**Pull request merged**
