### PR TITLE
feat(treesitter): add rule to check node on insert mode

### LINKED ISSUE #226: Rule using treesitter not working
### Description

I'm trying to add the following rule based on node type for rescript files.

```lua
Rule('<', '>', 'rescript')
    :with_pair(
      ts_conds.is_ts_node { 'type_identifier', 'parameters', 'let_declaration' }
    )
    :with_cr(cond.none())
```

Expected behavior:

```rescript
type names = array| <-- cursor here, press `<`
type names = array<|>
```

Parser:

```
type_declaration [0, 0] - [0, 18]
  type_identifier [0, 5] - [0, 10]
  type_identifier [0, 13] - [0, 18]
```

### Mapping <cr> bug

_No response_

### Steps to reproduce

https://user-images.githubusercontent.com/16160544/160417218-2acf866e-cf64-4492-960e-06d7175a84d4.mp4

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'


vim.cmd [[au BufRead,BufNewFile *.res set filetype=rescript]]

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'windwp/nvim-autopairs',
      },
      {
        'nvim-treesitter/nvim-treesitter',
        run = ':TSUpdate',
        config = function ()
          require('nvim-treesitter.configs').setup{
            ensure_installed = {"lua"},
            highlight = {
              enable = true
            }
          }
        end,
        requires = {
          {
            'nkrkv/nvim-treesitter-rescript',
            run = ':TSInstall rescript'
          }
        },
      }
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  local Rule = require 'nvim-autopairs.rule'
  local ts_conds = require 'nvim-autopairs.ts-conds'
  local cond = require 'nvim-autopairs.conds'
  local npairs = require 'nvim-autopairs'

  require('nvim-autopairs').setup()

  npairs.add_rules {
    Rule('<', '>', 'rescript')
      :with_pair(
        ts_conds.is_ts_node { 'type_identifier', 'parameters', 'let_declaration' }
      )
      :with_cr(cond.none()),
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing nvim-autopairs and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

### PR DESCRIPTION
**Pull request by aspeddro**
In insert mode the node at the cursor is `source_file`, in that case I should not look for the parent.

Fix #226

### CODE REVIEW

**Comment by aspeddro** [comment]
@windwp, could the second parameter be a function?

```lua
ts_conds.is_ts_node(
  {'type_identifier'}, 
  function()
    -- return { line, col }
    return vim.api.nvim_get_cursor(0)
  end
)
```

**Comment by windwp** [comment]
yes it can be a function

**Comment by aspeddro** [comment]
Updates:

Added a new function `ts_conds.when(callback, position)`

```lua
Rule("<", ">", { "rescript" }):with_pair(
    ts_conds.when(function(params)
      return params.type == 'type_identifier'
    end, function()
      local cursor = vim.api.nvim_win_get_cursor(0)
      return { cursor[1] - 1, cursor[2] - 1 }
    end)
),
```

`params` is a table with the following content:

```lua
{
  node = node, -- node class
  lang = string, -- language (util to check if it's in an injection, example markdown codeblock)
  type = string, -- type of node
  range = table, -- range of node {number, number, number, number}
  anonymous = string, -- anonymous node type
}
```

This allows the user to have more control over the rule. What do you think @windwp? Feel free for suggestions.

TODO:
- Fix tests and add more
- Update documentation

**Comment by windwp** [comment]
if you want to format you can make another PR for format code.
now you add the new thing and format on same PR so it hard to understand.

i think we can add your new condition. Maybe change a function name from "when" to another name "is_in_range": ).

**Comment by windwp** [comment]
nice can i merge :)

**Comment by aspeddro** [comment]
it's is ready.

**Pull request merged**
