### PR TITLE
Feat: Add the option mapping <C-h> to deleting a pair

### PR DESCRIPTION
**Pull request by jakubkaczor**
Regarding #193.

### CODE REVIEW

**Comment by windwp** [comment]
Thank LGTM
can you make the default to false?

**Comment by jakubkaczor** [comment]
> Thank LGTM can you make the default to false?

Yes, of course! But may I ask why? Perhaps not for `<C-w>`, but as the Neovim's default behavior of `<C-h>` is the same as of `<BS>`, it seems reasonable to make default plugin's behavior the same with respect to `<BS>` and `<C-h>`. Doesn't it?

**Comment by windwp** [comment]
c-h to delete is not familiar on Window I think it is more familiar on Mac.

 user will have another mapping on that key so better make it to false.

**Comment by jakubkaczor** [comment]
If I understood correctly, this is because you think it is more likely that a Windows user will have something else mapped to `<C-h>` in insert mode? Well, to me, remapping keys in insert mode seems quite rare in general, but maybe you meant some conflicting Windows mappings or different Neovim's defaults on this platform, which I don't know much about. Anyway, this is your project and I think discussing defaults is out of scope of this pull request, so I've made the changes you suggested, it defaults to `false` now. 😉 Thank you for this plugin. 😊

**Comment by windwp** [comment]
thank
 i search on github 
https://github.com/search?q=imap+c-h&type=code
😃

**Pull request merged**
