### PR TITLE
opposite direction for length in before_regex() condition

### LINKED ISSUE #440: opposite direction for length in before_regex() condition
### Description

When I specify the length in the `before_regex()` condition, I expect the string to grow in the opposite direction.

### Mapping <cr> bug

_No response_

### Steps to reproduce

```lua

npairs.add_rules {
  rule('with', ';', 'nix'):with_pair(conds.before_regex('^%s*wit$', 4)):with_cr(conds.none())
}
```

`nvim test.nix`

type something like:
`bla bla bla with`

but pair won't appear

### Minimal config

```Lua
npairs.add_rules {
  rule('with', ';', 'nix'):with_pair(conds.before_regex('^%s*wit$', 4)):with_cr(conds.none())
}
```

### PR DESCRIPTION
**Pull request by name-snrl**
fix #440

### CODE REVIEW

**Comment by windwp** [comment]
can you add test?

**Comment by name-snrl** [comment]
@windwp now sure is it correct, can you check it?

**Comment by name-snrl** [comment]
I'm also not sure about the `-- stylua: ignore` on top of the table with tests. But without it, it causes a lot of changes due to formatting, and also breaks alignment

**Comment by name-snrl** [comment]
@windwp fixed, rdy for merge

https://github.com/name-snrl/nvim-autopairs/actions/runs/8343766636

**Comment by windwp** [comment]
Ok , Thank

**Pull request merged**
