### PR TITLE
add installation instructions for vim-plug & Plug

### PR DESCRIPTION
**Pull request by Aym3nJ**

### CODE REVIEW

**Comment by cyril-s** [comment]
Thumbs up for his one :+1: 
For vim-plug I had to invoke lua part after `call plug#end()` though, like this:
```vim
" .config/neovim/init.vim

call plug#begin()
" other plugins
Plug 'windwp/nvim-autopairs'
call plug#end()

lua << EOF
require("nvim-autopairs").setup{}
EOF
```

**Comment by Aym3nJ** [comment]
> Thumbs up for his one +1 For vim-plug I had to invoke lua part after `call plug#end()` though, like this:
> 
> ```viml
> " .config/neovim/init.vim
> 
> call plug#begin()
> " other plugins
> Plug 'windwp/nvim-autopairs'
> call plug#end()
> 
> lua << EOF
> require("nvim-autopairs").setup{}
> EOF
> ```


Thanks man!
Should i add `call plug#begin()` and `call plug#end()` ? I'm not sure since i'm more of Packer user myself

**Comment by cyril-s** [comment]
@Aym3nJ yeah, It is how vim-plug works. Only after `call plug#end()` it updates `&runtimepath`. Also the process isn't 100% smooth because you need to run `:PlugInstall` to actually fetch a plugin. So the the steps that worked for me were:
1) Open nvim and run `:Plug 'windwp/nvim-autopairs'` and `:PlugInstall` after it
1) In `init.vim` add `Plug 'windwp/nvim-autopairs'` in plugin section, and `lua require("nvim-autopairs").setup{}` after `call plug#end()` and restart

**Comment by windwp** [comment]
can you remove a comment message inside a setup (). it make user can easy copy and paste and they still need delete that message.

**Comment by windwp** [comment]
can you remove a comment message inside a setup (). it make user can easy copy and paste and they still need delete that message.

**Comment by Aym3nJ** [comment]
> can you remove a comment message inside a setup (). it make user can easy copy and paste and they still need delete that message.

Yes sir, Done!

**Comment by windwp** [comment]
Thanks

**Pull request merged**
