### PR TITLE
<cmd> hack to not move the cursor for new pairs

### PR DESCRIPTION
**Pull request by Sam-programs**
this is a solution for the issue i pointed here 
https://github.com/windwp/nvim-autopairs/pull/393#issuecomment-1723249638
  
the way i fixed this is by adding a command `ReservedAutopairsJumptbackpairs` which positions the cursor in the correct place after custom pairs
which could also be added as a hotkey for jumping back to the position of the last pair (i don't think anyone needs that tho)  
i also removed recursive mapping from my last pr (sorry for the trouble)  
the commits are a mix of the old pr commits and this pr's commits as i couldn't fork twice (i am new to prs and i forgot to the delete the last fork) 
and there is a test failing on line 82 of test_utils.lua because i used `nvim_win_set_cursor`
and conflicts because i removed recursive mapping from my last pr

### CODE REVIEW

**Comment by Sam-programs** [comment]
i think the test are failing because they are checking for \<left\> s in the returned string  
because everything seems to work just fine maybe you could make a `utils.set_cursor` or something to make the code testable

**Comment by Sam-programs** [comment]
there are some conflicts now because i fixed another issue that was related to https://github.com/windwp/nvim-autopairs/pull/393#issuecomment-1726015808
sorry for being messy

**Comment by Sam-programs** [comment]
I AM SORRY FOR ALL THE ISSUES I MADE USING RECURSIVE MAPPING
i really didn't know users would actually remap the = key or the $ key

**Comment by windwp** [comment]
i forget about it too.
can you just delete your branch and create a new pr. now it conflict with another pr

**Comment by Sam-programs** [comment]
sure

**Pull request closed without merging**
