### PR TITLE
feat(move on empty function signature)

### PR DESCRIPTION
**Pull request by Sam-programs**
made the feature requested in #387

### CODE REVIEW

**Comment by windwp** [comment]
can you add a prefix enable_move_on_empty_functions.
there are some options don't have that prefix  because it come from old version and i don't want to break user config.

**Comment by Sam-programs** [comment]
done

**Comment by Sam-programs** [comment]
hmm i am actually a bit scared i might have broken some custom pairs
because i am not using key_map anymore
```lua
                local pairs = utils.esc(rule.start_pair .. rule.end_pair)
                local move_text = ''
                if  autopairs.config.move_on_empty_functions == false or 
                    functionsig:sub(#functionsig - 1,#functionsig) ~= pairs
                    then
                    move_text = utils.esc(utils.repeat_key('<left>',#rule.end_pair))
                end
                vim.api.nvim_feedkeys(pairs .. move_text, "i", false)
```
should i hardcore () as the function signature pair ?

**Comment by Sam-programs** [comment]
i am sure this is safe to add now

**Comment by Sam-programs** [comment]
i am sure this is safe to add now

**Pull request closed without merging**
