### PR TITLE
feat: allow python prefixed strings (f,b,r,u) with single quotes

### LINKED ISSUE #376: Inconsistent behavior with Python f-strings
### Description

nvim-autopairs behaves as expect with double quoted Python f-strings, but does not auto close for single quoted f-strings.

### Mapping <cr> bug

1.If you report a bug about indent. Please remember that plugin doesn't do anything about indent.
  It just trigger the indent of your vim config so if you have wrong indent config then it will do wrong indent.
  You can check by select a block of code and press `==`

2. provide result of command `:verbose imap <cr>`.
`
<CR>        * v:lua.MPairs.completion_confirm()
Last set from Lua
`

### Steps to reproduce

f-strings

`if"` creates the input `f"|"` as expected compared to inserting a non f-string. 
`if'` creates the input `f'|`, adding an additional single quote results in `f''|'`

`I'`, without the leading `f`, creates the input `'|'` as expected.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'windwp/nvim-autopairs',
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('nvim-autopairs').setup()
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing nvim-autopairs and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

### PR DESCRIPTION
**Pull request by ribru17**
Fixes #376

Allows autopairing of single quotes after `f`, `b`, `r`, `u` (and the capital variants).

### CODE REVIEW

**Comment by DenZhigalov** [comment]
Hi! I am just a random user. Just to let you know, I tried your version and behavior is still inconsistent for me.
input f"{ -> f"{}"
input f'{ -> f'{'}
If you don't mind please try that and tell me if that is something that still needs to be fixed or maybe that's just a problem with my config.

**Comment by ribru17** [comment]
Ahh, thanks for pointing this out :/ The issue I have found is that the check `is_in_quotes` fails (line 72) because there is a check that this will return false for single quotes following a word (to prevent it from thinking an apostrophe means it is inside a quote). I found a solution but I don't think it is a good one, it just hardcodes this part to pass when in Python. I think I will wait and see what @windwp thinks

**Comment by windwp** [comment]
can you add testcase.

**Comment by ribru17** [comment]
After working a bit, now I think it is not as easy. The bracket issue breaks due to the bracket rule thinking it is not in a quote (even though it is in this new case). So there would have to be some sort of change to the `is_in_quotes` function. However it may not be as bad as a Python workaround hard code. Maybe the function can take some optional parameter to override the regex with a new regex (e.g. the python prefixed string checker)?

**Comment by windwp** [comment]
@ribru17  Are you try to change the order of rule if you put your rule with f string first.
then you add rule is_in_quote  . then i think it should work

**Comment by ribru17** [comment]
@windwp Sorry not sure what you mean by that

**Comment by windwp** [comment]
@ribru17 sorry for late response. this PR is merged . I just modify some regex. https://github.com/windwp/nvim-autopairs/commit/8b41fe435e61e06e2202ac6802204746dad1089d . Thank you

**Pull request closed without merging**
