### PR TITLE
smoother custom pairs

### PR DESCRIPTION
**Pull request by Sam-programs**
https://github.com/windwp/nvim-autopairs/pull/396
sorry for bringing this up again but i tested nvim_win_set_cursor and it never broke the undo blocks only arrow keys broke them
```lua
vim.keymap.set("i", "<C-r>", function()
   local set_cursor = vim.api.nvim_win_set_cursor
   local r,c = unpack(vim.api.nvim_win_get_cursor(0))
   set_cursor(0,{r,c + 1})
   set_cursor(0,{r - 1,c + 2})
   set_cursor(0,{r - 1,c - 2})
   set_cursor(0,{1,0})
   set_cursor(0,{r,c})
end)
```
jump_to_last_pair is safe to add to make custom pairs smoother

### CODE REVIEW

**Comment by windwp** [comment]
On mapping, I want to use mapping by key only. Using API functions like set_cursor or set_text might interfere with other plugins. I'm not sure what you mean by 'smoother.' What does this pull request aim to achieve?.

**Comment by Sam-programs** [comment]
well say we define a custom rule for lua then's 
```
  rule("then","end","lua")
```
the cursor moves twice when we press n
```
 the|
 thene|nd
 then|end
```
because of ctrl-g

**Comment by Sam-programs** [comment]
i think i found a better way with lazy drawing

**Comment by Sam-programs** [comment]
yea this seems to make everything super clean with no weird cursor movements

**Comment by Sam-programs** [comment]
@windwp  here is what i mean by smoother

https://github.com/windwp/nvim-autopairs/assets/130783534/eddad57e-8dd3-4aa8-9347-1e3a609f0aa1

in the video it moves the cursor 2 times at second 5 and second 6(the end),
i am not even using `vim.api.*` functions anymore just setting lazy-redrawing
and sorry for the quality i didn't have my obs setup properly while recording this

**Comment by Sam-programs** [comment]
also can't we pre-escape keys in `utils.lua`
instead of having to call `utils.esc` each time we use them?

**Pull request closed without merging**
