### PR TITLE
Expose basic bracket

### PR DESCRIPTION
**Pull request by thecontinium**
Please see [here](https://github.com/windwp/nvim-autopairs/issues/300#issuecomment-1356081754)

### CODE REVIEW

**Comment by windwp** [comment]
hi thank 
may be change the name  from basic to quote is better.
and can you change that similar to it
``` lua
local function creator_quote(opt)
         return function quote( ...)

       end
end
```

it make we can use it  like this  quote("(", ")")

**Comment by thecontinium** [comment]
Hi - I'm not entirely sure what you mean; are you suggesting this: 

``` lua
local Rule = require("nvim-autopairs.rule")
local cond = require("nvim-autopairs.conds")

local function quote_creator(opt)
    local quote = function(...)
        local move_func = opt.enable_moveright and cond.move_right or cond.none
        local rule = Rule(...):with_move(move_func()):with_pair(cond.not_add_quote_inside_quote())

        if #opt.ignored_next_char > 1 then
            rule:with_pair(cond.not_after_regex(opt.ignored_next_char))
        end
        rule:use_undo(opt.break_undo)
        return rule
    end
    return quote
end

local function bracket_creator(opt)
    local quote = quote_creator(opt)
    local bracket = function(...)
        local rule = quote(...)
        if opt.enable_check_bracket_line == true then
            rule:with_pair(cond.is_bracket_line()):with_move(cond.is_bracket_line_move())
        end
        if opt.enable_bracket_in_quote then
            -- still add bracket if text is quote "|" and next_char have "
            rule:with_pair(cond.is_bracket_in_quote(), 1)
        end
        return rule
    end
    return bracket
end

local function setup(opt)
    -- stylua: ignore
    local quote = quote_creator(opt)
    local bracket = bracket_creator(opt)
    local rules = {
        Rule("<!--", "-->", "html"):with_cr(cond.none()),
        Rule("```", "```", { "markdown", "vimwiki", "rmarkdown", "rmd", "pandoc" }),
        Rule("```.*$", "```", { "markdown", "vimwiki", "rmarkdown", "rmd", "pandoc" }):only_cr():use_regex(true),
        Rule('"""', '"""', { "python", "elixir", "julia", "kotlin" }):with_pair(cond.not_before_char('"', 3)),
        Rule("'''", "'''", { "python" }):with_pair(cond.not_before_char('"', 3)),
        quote("'", "'", "-rust"):with_pair(cond.not_before_regex("%w")),
        quote("'", "'", "rust"):with_pair(cond.not_before_regex("[%w<&]")):with_pair(cond.not_after_text(">")),
        quote("`", "`"),
        quote('"', '"', "-vim"),
        quote('"', '"', "vim"):with_pair(cond.not_before_regex("^%s*$", -1)),
        bracket("(", ")"),
        bracket("[", "]"),
        bracket("{", "}"),
        Rule(
            ">[%w%s]*$",
            "^%s*</",
            {
                "html",
                "typescript",
                "typescriptreact",
                "javascript",
                "javascriptreact",
                "svelte",
                "vue",
                "xml",
                "rescript",
            }
        ):only_cr():use_regex(true),
    }
    return rules
end

return { setup = setup, quote_creator = quote_creator, bracket_creator = bracket_creator }
```

which can then be used like this

``` lua
local npairs = require("nvim-autopairs")
local cond = require("nvim-autopairs.conds")
local basic = require("nvim-autopairs.rules.basic")

npairs.setup()

-- this in effect uses the default behaviour and adds +,-,/,* to no after
local bracket = basic.bracket_creator(require("nvim-autopairs").config)
npairs.add_rules({
	bracket("(", ")", { "clojure", "lisp" })
		:with_pair(cond.not_after_regex([=[[%w%%%'%[%"%.%`%$%+%-%/%*]]=])),
})

-- turn off the orighinal rule for clojure and lisp
npairs.get_rule("(")[1].not_filetypes = { "clojure", "lisp" }
```

**Comment by thecontinium** [comment]
I have updated to use creator functions

**Comment by windwp** [comment]
some test case depend on treesitter is not working maybe nvim-treesitter is update

**Comment by thecontinium** [comment]
I don’t think this this is anything to do with my changes. Can you run the tests on the current head to confirm this ?

--
The Continium

On 7 January 2023 at 04:00:19, windwp ***@***.******@***.***>) wrote:

some test case depend on treesitter is not working maybe nvim-treesitter is update

**Comment by windwp** [comment]
Thank

**Pull request merged**
