### PR TITLE
feat: added ignored_next_char options

### PR DESCRIPTION
**Pull request by elianiva**
#17 
I'm still unsure with the option name.

### CODE REVIEW

**Comment by windwp** [comment]
Can you change name to  ignore_pattern and use a string not a boolean. 
it will better if user can change it.
Thank

**Comment by elianiva** [comment]
Ah yes, I agree.

**Comment by elianiva** [comment]
I think this is ready to merge.

**Comment by abenz1267** [comment]
Quick question, i have this setup:

`require('nvim-autopairs').setup {ignored_next_char = "[^%]%)%}%>%<]"}`

But for example here 
```go
func someThing() <HERE> {
...
```
It's not adding a closing bracket, i ASSUME because "ignored_next_char" ignores whitespace and actually looks for the next non-whitespace character, is that correct?

Can this be fixed or do i need to change something?

Regards

**Pull request merged**
